# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('name', models.TextField()),
                ('language', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.URLField()),
                ('user_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.Repository'),
        ),
    ]
