# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20161103_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='stargazers_count',
            field=models.IntegerField(null=True),
        ),
    ]
