# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:09
from __future__ import unicode_literals

from django.db import migrations


def do_stuff(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Repository = apps.get_model("github", "Repository")
    for repo in Repository.objects.all():
        repo.stargazers_count = repo.raw_data['stargazers_count']
        repo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_repository_stargazers_count'),
    ]

    operations = [
        migrations.RunPython(do_stuff),
    ]
