# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20161108_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='stargazers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
